package com.example.urlshortener.application.service;

import com.example.urlshortener.domain.exception.CustomAliasAlreadyExistsException;
import com.example.urlshortener.domain.exception.InvalidCustomAliasException;
import com.example.urlshortener.domain.exception.UrlExpiredException;
import com.example.urlshortener.domain.model.ClickEvent;
import com.example.urlshortener.domain.model.UrlMapping;
import com.example.urlshortener.domain.port.out.CachePort;
import com.example.urlshortener.domain.port.out.EventPublisherPort;
import com.example.urlshortener.domain.port.out.UrlRepositoryPort;
import com.example.urlshortener.domain.util.Base62Encoder;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Optional;
import java.util.Set;
import java.util.regex.Pattern;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@RequiredArgsConstructor
public class UrlShortenerService {

    private static final Pattern ALIAS_PATTERN = Pattern.compile("^[a-zA-Z0-9_-]{3,30}$");
    private static final Set<String> RESERVED_KEYWORDS = Set.of(
            "api", "actuator", "stats", "health", "metrics", "prometheus", "admin", "assets", "favicon.ico"
    );

    private final UrlRepositoryPort urlRepository;
    private final CachePort cachePort;
    private final EventPublisherPort eventPublisher;

    public UrlMapping shortenUrl(String originalUrl) {
        return shortenUrl(originalUrl, null, null);
    }

    public UrlMapping shortenUrl(String originalUrl, String customAlias) {
        return shortenUrl(originalUrl, customAlias, null);
    }

    @Transactional
    public UrlMapping shortenUrl(String originalUrl, String customAlias, LocalDateTime expiresAt) {
        LocalDateTime effectiveExpiresAt = expiresAt != null 
                ? expiresAt 
                : LocalDateTime.now(ZoneId.systemDefault()).plusDays(30);
        
        validateExpiresAt(effectiveExpiresAt);

        if (customAlias != null && !customAlias.isBlank()) {
            String trimmedAlias = customAlias.trim();
            validateCustomAlias(trimmedAlias);
            return createCustomMapping(originalUrl, trimmedAlias, effectiveExpiresAt);
        }

        return createAutoGeneratedMapping(originalUrl, effectiveExpiresAt);
    }

    @Transactional
    public void deleteUrl(String shortCode) {
        urlRepository.deleteByShortCode(shortCode);
        cachePort.evict(shortCode);
    }

    private void validateExpiresAt(LocalDateTime expiresAt) {
        LocalDateTime now = LocalDateTime.now(ZoneId.systemDefault());
        if (expiresAt.isBefore(now)) {
            throw new IllegalArgumentException("Expiration date must be in the future.");
        }

        LocalDateTime maxAllowed = now.plusMonths(6);
        if (expiresAt.isAfter(maxAllowed)) {
            throw new IllegalArgumentException("Expiration date cannot exceed 6 months into the future.");
        }
    }

    private void validateCustomAlias(String alias) {
        if (!ALIAS_PATTERN.matcher(alias).matches()) {
            throw new InvalidCustomAliasException("Custom alias must be between 3 and 30 characters long and contain only letters, numbers, underscores, or hyphens.");
        }

        if (RESERVED_KEYWORDS.contains(alias.toLowerCase())) {
            throw new InvalidCustomAliasException("The custom alias '" + alias + "' is a reserved keyword.");
        }

        // Check availability in Redis or Database
        if (cachePort.get(alias).isPresent() || urlRepository.findByShortCode(alias).isPresent()) {
            throw new CustomAliasAlreadyExistsException(alias);
        }
    }

    private UrlMapping createCustomMapping(String originalUrl, String customAlias, LocalDateTime expiresAt) {
        LocalDateTime now = LocalDateTime.now(ZoneId.systemDefault());
        UrlMapping mapping = UrlMapping.builder()
                .originalUrl(originalUrl)
                .shortCode(customAlias)
                .createdAt(now)
                .expiresAt(expiresAt)
                .clickCount(0)
                .build();

        UrlMapping saved = urlRepository.save(mapping);
        cacheInRedis(customAlias, originalUrl, expiresAt, now);
        return saved;
    }

    private UrlMapping createAutoGeneratedMapping(String originalUrl, LocalDateTime expiresAt) {
        LocalDateTime now = LocalDateTime.now(ZoneId.systemDefault());
        UrlMapping initialMapping = UrlMapping.builder()
                .originalUrl(originalUrl)
                .createdAt(now)
                .expiresAt(expiresAt)
                .clickCount(0)
                .build();

        UrlMapping savedMapping = urlRepository.save(initialMapping);
        String shortCode = Base62Encoder.encode(savedMapping.getId());
        savedMapping.setShortCode(shortCode);

        UrlMapping updated = urlRepository.save(savedMapping);
        cacheInRedis(shortCode, originalUrl, expiresAt, now);
        return updated;
    }

    private void cacheInRedis(String shortCode, String originalUrl, LocalDateTime expiresAt, LocalDateTime now) {
        if (expiresAt != null) {
            Duration ttl = Duration.between(now, expiresAt);
            if (!ttl.isNegative() && !ttl.isZero()) {
                cachePort.put(shortCode, originalUrl, ttl);
                return;
            }
        }
        cachePort.put(shortCode, originalUrl);
    }

    public Optional<String> getOriginalUrlAndTrackClick(String shortCode, String ipAddress, String userAgent) {
        // 1. Check DB Mapping for expiration and validity
        Optional<UrlMapping> dbMapping = urlRepository.findByShortCode(shortCode);
        if (dbMapping.isPresent()) {
            UrlMapping mapping = dbMapping.get();
            if (mapping.getExpiresAt() != null && LocalDateTime.now(ZoneId.systemDefault()).isAfter(mapping.getExpiresAt())) {
                cachePort.evict(shortCode);
                throw new UrlExpiredException(shortCode);
            }

            // 2. Check Redis Cache
            Optional<String> cachedUrl = cachePort.get(shortCode);
            if (cachedUrl.isPresent()) {
                publishClickAsync(shortCode, ipAddress, userAgent);
                return cachedUrl;
            }

            // Cache miss -> Put in Redis and return
            String originalUrl = mapping.getOriginalUrl();
            cacheInRedis(shortCode, originalUrl, mapping.getExpiresAt(), LocalDateTime.now(ZoneId.systemDefault()));
            publishClickAsync(shortCode, ipAddress, userAgent);
            return Optional.of(originalUrl);
        }

        return Optional.empty();
    }

    private void publishClickAsync(String shortCode, String ipAddress, String userAgent) {
        ClickEvent event = ClickEvent.builder()
                .shortCode(shortCode)
                .ipAddress(ipAddress)
                .userAgent(userAgent)
                .timestamp(LocalDateTime.now(ZoneId.systemDefault()))
                .build();
        eventPublisher.publishClickEvent(event);
    }
}
