package com.example.urlshortener.application.service;

import com.example.urlshortener.domain.exception.CustomAliasAlreadyExistsException;
import com.example.urlshortener.domain.exception.InvalidCustomAliasException;
import com.example.urlshortener.domain.model.ClickEvent;
import com.example.urlshortener.domain.model.UrlMapping;
import com.example.urlshortener.domain.port.out.CachePort;
import com.example.urlshortener.domain.port.out.EventPublisherPort;
import com.example.urlshortener.domain.port.out.UrlRepositoryPort;
import com.example.urlshortener.domain.util.Base62Encoder;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Optional;
import java.util.Set;
import java.util.regex.Pattern;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
public class UrlShortenerService {

    private static final Pattern ALIAS_PATTERN = Pattern.compile("^[a-zA-Z0-9_-]{3,30}$");
    private static final Set<String> RESERVED_KEYWORDS = Set.of(
            "api", "actuator", "stats", "health", "metrics", "prometheus", "admin", "assets", "favicon.ico"
    );

    private final UrlRepositoryPort urlRepository;
    private final CachePort cachePort;
    private final EventPublisherPort eventPublisher;

    public UrlMapping shortenUrl(String originalUrl) {
        return shortenUrl(originalUrl, null);
    }

    public UrlMapping shortenUrl(String originalUrl, String customAlias) {
        if (customAlias != null && !customAlias.isBlank()) {
            String trimmedAlias = customAlias.trim();
            validateCustomAlias(trimmedAlias);
            return createCustomMapping(originalUrl, trimmedAlias);
        }

        return createAutoGeneratedMapping(originalUrl);
    }

    private void validateCustomAlias(String alias) {
        if (!ALIAS_PATTERN.matcher(alias).matches()) {
            throw new InvalidCustomAliasException("Custom alias must be between 3 and 30 characters long and contain only letters, numbers, underscores, or hyphens.");
        }

        if (RESERVED_KEYWORDS.contains(alias.toLowerCase())) {
            throw new InvalidCustomAliasException("The custom alias '" + alias + "' is a reserved keyword.");
        }

        // Check availability in Redis or Database
        if (cachePort.get(alias).isPresent() || urlRepository.findByShortCode(alias).isPresent()) {
            throw new CustomAliasAlreadyExistsException(alias);
        }
    }

    private UrlMapping createCustomMapping(String originalUrl, String customAlias) {
        UrlMapping mapping = UrlMapping.builder()
                .originalUrl(originalUrl)
                .shortCode(customAlias)
                .createdAt(LocalDateTime.now(ZoneId.systemDefault()))
                .clickCount(0)
                .build();

        UrlMapping saved = urlRepository.save(mapping);
        cachePort.put(customAlias, originalUrl);
        return saved;
    }

    private UrlMapping createAutoGeneratedMapping(String originalUrl) {
        UrlMapping initialMapping = UrlMapping.builder()
                .originalUrl(originalUrl)
                .createdAt(LocalDateTime.now(ZoneId.systemDefault()))
                .clickCount(0)
                .build();

        UrlMapping savedMapping = urlRepository.save(initialMapping);
        String shortCode = Base62Encoder.encode(savedMapping.getId());
        savedMapping.setShortCode(shortCode);

        UrlMapping updated = urlRepository.save(savedMapping);
        cachePort.put(shortCode, originalUrl);
        return updated;
    }

    public Optional<String> getOriginalUrlAndTrackClick(String shortCode, String ipAddress, String userAgent) {
        // 1. Check Redis Cache
        Optional<String> cachedUrl = cachePort.get(shortCode);
        if (cachedUrl.isPresent()) {
            publishClickAsync(shortCode, ipAddress, userAgent);
            return cachedUrl;
        }

        // 2. Cache Miss -> Check DB
        Optional<UrlMapping> dbMapping = urlRepository.findByShortCode(shortCode);
        if (dbMapping.isPresent()) {
            String originalUrl = dbMapping.get().getOriginalUrl();
            cachePort.put(shortCode, originalUrl);
            publishClickAsync(shortCode, ipAddress, userAgent);
            return Optional.of(originalUrl);
        }

        return Optional.empty();
    }

    private void publishClickAsync(String shortCode, String ipAddress, String userAgent) {
        ClickEvent event = ClickEvent.builder()
                .shortCode(shortCode)
                .ipAddress(ipAddress)
                .userAgent(userAgent)
                .timestamp(LocalDateTime.now(ZoneId.systemDefault()))
                .build();
        eventPublisher.publishClickEvent(event);
    }
}
